### ISSUE TITLE
RSS Feed XML with custom timezone

### ISSUE THREAD

**Issue by louanfontenele** [eikowagenknecht/lootscraper#126]
### Is your feature request related to a problem? Please describe.

It would be interesting if the rss feed (https://feed.phenx.de/lootscraper_amazon_game.xml) had a parameter to set a time zone.

### Describe the solution you'd like

An example could be like this: https://feed.phenx.de/lootscraper_amazon_game.xml?tz=utc-3

**Comment by eikowagenknecht** [comment]
The feeds are static files. To add the feature you suggest, there would need to be processing on the server side. I currently do not plan to add that as it would add quite a lot of complexity.

The actual times in the feed are already timezone-aware (e.g. 2022-12-27T17:02:28.170165+00:00). So the "valid from" (which is the same as the "published" date in the feed, already can be parsed by your feed reader of choice to show the time in your time zone. Only the text in the feed itself can't.
