### ISSUE TITLE
Prime Gaming In-Game Loot Not Working

### ISSUE THREAD

**Issue by IPFizzy** [eikowagenknecht/lootscraper#209]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

The Prime Gaming in-game loot rss feed hasn't gotten any updates for 60+ days. The free games for prime seems to be working fine, but no new updates for the in-game loot.

**Comment by eikowagenknecht** [comment]
Thanks for the heads up, will look at it shortly. Probably Amazon changed the page layout.

**Comment by IPFizzy** [comment]
No problem! Hope to see it fixed.

**Comment by eikowagenknecht** [comment]
Fixed with commit [16802ae](https://github.com/eikowagenknecht/lootscraper/pull/212/commits/16802ae07cd4a11fbe1882242aae1f90b6bf1d23), new offers will come in shortly.
