### ISSUE TITLE
Add support for itch.io

### ISSUE THREAD

**Issue by eikowagenknecht** [eikowagenknecht/lootscraper#21]
On itch.io there are some offers as well that could be included. The difficult thing here is to distinguish between real offers and low quality games. An approach would be to use https://itch.io/games/new-and-popular/on-sale as a starting point and include all games that cost 0€ and also have a discount of 100% (meaning they are not always free).

Unfortunately this mostly includes games with a recommended price of 1.00€ and low quality. This is probably not what users want to see when they look for free offers. So we would neet another metric to determine the "wantedness" of an offer. The recommended selling price? A rating score?

Not sure if it's worth including this site for the few real offers it sometimes contains.

**Comment by eikowagenknecht** [comment]
The games that are always free can be put in their own feed (see #60)

**Comment by poudink** [comment]
As a user, of the current feeds, I'd personally be much more interested in seeing all of the offers regardless of "wantedness" and deciding for myself which ones I'm interested in.

**Comment by eikowagenknecht** [comment]
I tend to agree, if nothing else it's way easier to implement it that way. Will take a look at it shortly.

**Comment by eikowagenknecht** [comment]
I have a working implementation for gabes with 100% discount (currently ~50 games). As for the "always free" part I think itch.io has just too many offers for this to make any sense. On https://itch.io/games/new-and-popular/free/last-day there have been ~700 new free games *in the last day*. What's your thought @poudink ?

**Comment by eikowagenknecht** [comment]
Implemented in #61 for offers

**Comment by poudink** [comment]
I'm not too interested in the "always free" offers. Freeware is more than common enough for me to get by without a feed.
