### ISSUE TITLE
Support for Apprise for notification handling

### ISSUE THREAD

**Issue by Nuuki9** [eikowagenknecht/lootscraper#215]
### Is your feature request related to a problem? Please describe.

I see there's already a FR for adding Discord notificiation support. I would instead suggest adding support for [Apprise](https://github.com/caronc/apprise) - this is a lightweight notification system that supports a huge list of services. That includes Discord, but adds a ton more as well.

### Describe the solution you'd like

Support for Apprise as a mechanism to configure notifications.

**Comment by eikowagenknecht** [comment]
Unfortunately, I don't have enough free time at the moment to do more than maintenance and small improvements, so the Discord bot won't happen any time soon.

I think MonitoRSS will be a good workaround for a lot of use cases and have added a short paragraph on how to configure it to the README. I'll be closing all Discord related issues for the time being.
