### ISSUE TITLE
Support for Twitch Drops

### ISSUE THREAD

**Issue by MEGAMENE** [eikowagenknecht/lootscraper#235]
### Is your feature request related to a problem? Please describe.

Add support for Twitch Drops.

**Comment by eikowagenknecht** [comment]
I'll have a look at it. Seems like the overview would be here: https://www.twitch.tv/drops/campaigns

**Comment by eikowagenknecht** [comment]
Unfortunately, the list is only available if you are logged in. And logging in seems to be quite scraping-resistant. I couldn't get around the "Your browser is not currently supported. Please use a [recommended browser](https://help.twitch.tv/s/article/supported-browsers) or learn more [here](https://help.twitch.tv/s/article/supported-browsers)." message.

Do you know of any openly available (without login) list of Twitch drops?

**Comment by eikowagenknecht** [comment]
Closing this as unplanned as there is currently no way to see the Twitch drops without logging in. If you know one, leave a comment and I'll reopen.
