### ISSUE TITLE
Missing Epic Games' free game this week

### ISSUE THREAD

**Issue by Janglinator** [eikowagenknecht/lootscraper#247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The most recent Epic Games free game hasn't appeared in any of the feeds

### Expected Behavior

The most recent Epic Games free game appears in the feeds

### Steps To Reproduce

- Check Epic Games' website ([https://store.epicgames.com/en-US/free-games](https://store.epicgames.com/en-US/free-games))
- Latest free game popped up this morning (911 Operator)
- Check lootscraper's RSS ([https://feed.phenx.de/lootscraper_epic_game.xml](https://feed.phenx.de/lootscraper_epic_game.xml)
- 911 Operator doesn't appear

**Comment by eikowagenknecht** [comment]
Thanks for the info, seeing some unusual resource usage on the server side. Will have a detailled look tomorrow.

**Comment by eikowagenknecht** [comment]
The problem was with another Docker container running on the same NAS that grabbed too much RAM, leaving none for Lootscraper. Restarted the host and now it's working just fine again.

**Comment by Janglinator** [comment]
Thanks for giving it a look!

**Comment by Janglinator** [comment]
Unfortunately, it looks like it's a persisting issue

**Comment by eikowagenknecht** [comment]
Nope, just got the offer. The scraping is running about every 20 minutes currently, so there might be a slight delay, depending on the actual time it runs.

If one day it’s not there by 6pm CET, feel free to reopen this issue 😊

**Comment by Janglinator** [comment]
There it is!  I guess I was just a little too impatient 😄

**Comment by RoseTheFlower** [comment]
This week's games are also missing.

**Comment by eikowagenknecht** [comment]
Seems like epic changed the layout again.. I‘m not at home for the next week, but will have a look at it shortly after 👍

**Comment by Cla33ic** [comment]
hey, looked into it and this is working for me:

//src/lootscraper/scraper/epic_games.py

`from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import TYPE_CHECKING

import schedule
from playwright.async_api import Error

from lootscraper.browser import get_new_page
from lootscraper.common import OfferDuration, OfferType, Source
from lootscraper.database import Offer
from lootscraper.scraper.scraper_base import OfferHandler, RawOffer, Scraper

if TYPE_CHECKING:
    from playwright.async_api import Locator, Page

logger = logging.getLogger(__name__)

BASE_URL = "https://store.epicgames.com"
OFFER_URL = BASE_URL + "/en-US/"


@dataclass(kw_only=True)
class EpicRawOffer(RawOffer):
    valid_to: str


class EpicGamesScraper(Scraper):
    @staticmethod
    def get_source() -> Source:
        return Source.EPIC

    @staticmethod
    def get_type() -> OfferType:
        return OfferType.GAME

    @staticmethod
    def get_schedule() -> list[schedule.Job]:
        return [
            schedule.every().day.at("11:05", "US/Eastern"),
            schedule.every().day.at("13:00", "US/Eastern"),
        ]

    @staticmethod
    def get_duration() -> OfferDuration:
        return OfferDuration.CLAIMABLE

    def offers_expected(self) -> bool:
        return True

    def get_offers_url(self) -> str:
        return OFFER_URL

    def get_page_ready_selector(self) -> str:
        return "h5:has-text('Free Games')"

    async def scrape(self) -> list[Offer]:
        logger.debug(f"Starting scrape for {self.get_source().value}")
        
        async with get_new_page(self.context) as page:
            logger.debug(f"Navigating to {self.get_offers_url()}")
            try:
                await page.goto(self.get_offers_url(), timeout=30000)
                logger.debug("Page loaded successfully")
            except Error:
                logger.exception("Couldn't load page")
                return []

            logger.debug"Starting page_loaded_hook (scrolling)")
            await self.page_loaded_hook(page)
            logger.debug("page_loaded_hook (scrolling) completed")

            logger.debug(f"Waiting for selector: {self.get_page_ready_selector()}")
            try:
                await page.wait_for_selector(self.get_page_ready_selector(), timeout=10000)
                logger.debug("Page ready selector found")
            except Error:
                logger.exception("Page ready selector not found")
                return []

            logger.debug("Starting to read offers")
            offers = await self.read_offers(page)
            logger.debug(f"Found {len(offers)} raw offers")

        logger.debug("Cleaning and processing offers")
        offers = self.clean_offers(offers)
        unique_offers = self.deduplicate_offers(offers)
        categorized_offers = self.categorize_offers(unique_offers)
        filtered_offers = self.filter_for_valid_offers(categorized_offers)

        logger.debug(f"Final number of valid offers: {len(filtered_offers)}")
        return filtered_offers

    async def page_loaded_hook(self, page: Page) -> None:
        logger.debug("Starting to scroll")
        await page.evaluate("window.scrollBy(0, 2000)")
        logger.debug("Scroll completed, waiting for 2 seconds")
        await page.wait_for_timeout(2000)
        logger.debug("Wait completed")

    async def read_offers(self, page: Page) -> list[Offer]:
        offers: list[Offer] = []
        for handler in self.get_offer_handlers(page):
            logger.debug(f"Processing offer handler: {handler}")
            offers_locator = handler.locator

            try:
                elements = await offers_locator.all()
                logger.debug(f"Found {len(elements)} elements")
            except Error:
                logger.exception("Couldn't find any offers")
                return []

            for i, element in enumerate(elements):
                logger.debug(f"Processing element {i+1}/{len(elements)}")
                try:
                    raw_offer = await handler.read_offer_func(element)
                    if raw_offer is None:
                        logger.debug(f"Element {i+1} did not yield a raw offer")
                        continue
                    logger.debug(f"Raw offer found: {raw_offer}")
                except Exception:
                    logger.exception(f"Couldn't parse element {i+1}")
                    continue

                try:
                    normalized_offer = handler.normalize_offer_func(raw_offer)
                    logger.debug(f"Normalized offer: {normalized_offer}")
                except Exception:
                    logger.exception(f"Couldn't normalize offer {raw_offer.title}")
                    continue

                offers.append(normalized_offer)

        return offers

    def get_offer_handlers(self, page: Page) -> list[OfferHandler]:
        return [
            OfferHandler(
                page.locator('//span[text()="Free Now"]//ancestor::a'),
                self.read_raw_offer,
                self.normalize_offer,
            ),
        ]

    async def read_raw_offer(self, element: Locator) -> RawOffer:
        logger.debug("Starting to read raw offer")
        await element.scroll_into_view_if_needed()
        logger.debug("Element scrolled into view")

        title = await element.locator("//h6").text_content()
        if title is None:
            logger.error("Couldn't find title")
            raise ValueError("Couldn't find title")
        logger.debug(f"Found title: {title}")

        valid_to = await element.locator('//span[text()="Free Now - "]/time[1]').get_attribute("datetime")
        if valid_to is None:
            logger.error(f"Couldn't find valid to for {title}")
            raise ValueError(f"Couldn't find valid to for {title}")
        logger.debug(f"Found valid_to: {valid_to}")

        url = await element.get_attribute("href")
        if url is None:
            logger.error(f"Couldn't find url for {title}")
            raise ValueError(f"Couldn't find url for {title}")
        if not url.startswith("http"):
            url = BASE_URL + url
        logger.debug(f"Found url: {url}")

        img_url = await element.locator("img").get_attribute("src")
        if img_url is None:
            logger.error(f"Couldn't find image for {title}")
            raise ValueError(f"Couldn't find image for {title}")
        logger.debug(f"Found img_url: {img_url}")

        return EpicRawOffer(title=title, valid_to=valid_to, url=url, img_url=img_url)

    def normalize_offer(self, raw_offer: RawOffer) -> Offer:
        if not isinstance(raw_offer, EpicRawOffer):
            raise TypeError("Wrong type of raw offer")

        rawtext = {"title": raw_offer.title, "enddate": raw_offer.valid_to}

        utc_valid_to = None
        if raw_offer.valid_to:
            try:
                utc_valid_to = datetime.strptime(raw_offer.valid_to, "%Y-%m-%dT%H:%M:%S.000Z").replace(tzinfo=timezone.utc)
            except ValueError:
                logger.exception(f"Couldn't parse valid_to date: {raw_offer.valid_to}")

        return Offer(
            source=EpicGamesScraper.get_source(),
            duration=EpicGamesScraper.get_duration(),
            type=EpicGamesScraper.get_type(),
            title=raw_offer.title,
            probable_game_name=raw_offer.title,
            seen_last=datetime.now(timezone.utc),
            valid_to=utc_valid_to,
            rawtext=rawtext,
            url=raw_offer.url,
            img_url=raw_offer.img_url,
        )`

**Comment by Cla33ic** [comment]
Hey, i looked into it and that is working fine for me.

```python
from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import TYPE_CHECKING

import schedule
from playwright.async_api import Error

from lootscraper.browser import get_new_page
from lootscraper.common import OfferDuration, OfferType, Source
from lootscraper.database import Offer
from lootscraper.scraper.scraper_base import OfferHandler, RawOffer, Scraper

if TYPE_CHECKING:
    from playwright.async_api import Locator, Page

logger = logging.getLogger(__name__)

BASE_URL = "https://store.epicgames.com"
OFFER_URL = BASE_URL + "/en-US/"


@dataclass(kw_only=True)
class EpicRawOffer(RawOffer):
    valid_to: str


class EpicGamesScraper(Scraper):
    @staticmethod
    def get_source() -> Source:
        return Source.EPIC

    @staticmethod
    def get_type() -> OfferType:
        return OfferType.GAME

    @staticmethod
    def get_schedule() -> list[schedule.Job]:
        return [
            schedule.every().day.at("11:05", "US/Eastern"),
            schedule.every().day.at("13:00", "US/Eastern"),
        ]

    @staticmethod
    def get_duration() -> OfferDuration:
        return OfferDuration.CLAIMABLE

    def offers_expected(self) -> bool:
        return True

    def get_offers_url(self) -> str:
        return OFFER_URL

    def get_page_ready_selector(self) -> str:
        return "h5:has-text('Free Games')"

    async def scrape(self) -> list[Offer]:
        logger.debug(f"Starting scrape for {self.get_source().value}")
        
        async with get_new_page(self.context) as page:
            logger.debug(f"Navigating to {self.get_offers_url()}")
            try:
                await page.goto(self.get_offers_url(), timeout=30000)
                logger.debug("Page loaded successfully")
            except Error:
                logger.exception("Couldn't load page")
                return []

            logger.debug("Starting page_loaded_hook (scrolling)")
            await self.page_loaded_hook(page)
            logger.debug("page_loaded_hook (scrolling) completed")

            logger.debug(f"Waiting for selector: {self.get_page_ready_selector()}")

            try:
                await page.wait_for_selector(self.get_page_ready_selector(), timeout=10000)
                logger.debug("Page ready selector found")
            except Error:
                logger.exception("Page ready selector not found")
                return []

            logger.debug("Starting to read offers")
            offers = await self.read_offers(page)
            logger.debug(f"Found {len(offers)} raw offers")

        logger.debug("Cleaning and processing offers")
        offers = self.clean_offers(offers)
        unique_offers = self.deduplicate_offers(offers)
        categorized_offers = self.categorize_offers(unique_offers)
        filtered_offers = self.filter_for_valid_offers(categorized_offers)

        logger.debug(f"Final number of valid offers: {len(filtered_offers)}")
        return filtered_offers

    async def page_loaded_hook(self, page: Page) -> None:
        logger.debug("Starting to scroll")
        await page.evaluate("window.scrollBy(0, 2000)")
        logger.debug("Scroll completed, waiting for 2 seconds")
        await page.wait_for_timeout(2000)
        logger.debug("Wait completed")

    async def read_offers(self, page: Page) -> list[Offer]:
        offers: list[Offer] = []
        for handler in self.get_offer_handlers(page):
            logger.debug(f"Processing offer handler: {handler}")
            offers_locator = handler.locator

            try:
                elements = await offers_locator.all()
                logger.debug(f"Found {len(elements)} elements")
            except Error:
                logger.exception("Couldn't find any offers")
                return []

            for i, element in enumerate(elements):
                logger.debug(f"Processing element {i+1}/{len(elements)}")
                try:
                    raw_offer = await handler.read_offer_func(element)
                    if raw_offer is None:
                        logger.debug(f"Element {i+1} did not yield a raw offer")
                        continue
                    logger.debug(f"Raw offer found: {raw_offer}")
                except Exception:
                    logger.exception(f"Couldn't parse element {i+1}")
                    continue

                try:
                    normalized_offer = handler.normalize_offer_func(raw_offer)
                    logger.debug(f"Normalized offer: {normalized_offer}")
                except Exception:
                    logger.exception(f"Couldn't normalize offer {raw_offer.title}")
                    continue

                offers.append(normalized_offer)

        return offers

    def get_offer_handlers(self, page: Page) -> list[OfferHandler]:
        return [
            OfferHandler(
                page.locator('//span[text()="Free Now"]//ancestor::a'),
                self.read_raw_offer,
                self.normalize_offer,
            ),
        ]

    async def read_raw_offer(self, element: Locator) -> RawOffer:
        logger.debug("Starting to read raw offer")
        await element.scroll_into_view_if_needed()
        logger.debug("Element scrolled into view")

        title = await element.locator("//h6").text_content()
        if title is None:
            logger.error("Couldn't find title")
            raise ValueError("Couldn't find title")
        logger.debug(f"Found title: {title}")

        valid_to = await element.locator('//span[text()="Free Now - "]/time[1]').get_attribute("datetime")
        if valid_to is None:
            logger.error(f"Couldn't find valid to for {title}")
            raise ValueError(f"Couldn't find valid to for {title}")
        logger.debug(f"Found valid_to: {valid_to}")

        url = await element.get_attribute("href")
        if url is None:
            logger.error(f"Couldn't find url for {title}")
            raise ValueError(f"Couldn't find url for {title}")
        if not url.startswith("http"):
            url = BASE_URL + url
        logger.debug(f"Found url: {url}")

        img_url = await element.locator("img").get_attribute("src")
        if img_url is None:
            logger.error(f"Couldn't find image for {title}")
            raise ValueError(f"Couldn't find image for {title}")
        logger.debug(f"Found img_url: {img_url}")

        return EpicRawOffer(title=title, valid_to=valid_to, url=url, img_url=img_url)

    def normalize_offer(self, raw_offer: RawOffer) -> Offer:
        if not isinstance(raw_offer, EpicRawOffer):
            raise TypeError("Wrong type of raw offer")

        rawtext = {"title": raw_offer.title, "enddate": raw_offer.valid_to}

        utc_valid_to = None
        if raw_offer.valid_to:
            try:
                utc_valid_to = datetime.strptime(raw_offer.valid_to, "%Y-%m-%dT%H:%M:%S.000Z").replace(tzinfo=timezone.utc)
            except ValueError:
                logger.exception(f"Couldn't parse valid_to date: {raw_offer.valid_to}")

        return Offer(
            source=EpicGamesScraper.get_source(),
            duration=EpicGamesScraper.get_duration(),
            type=EpicGamesScraper.get_type(),
            title=raw_offer.title,
            probable_game_name=raw_offer.title,
            seen_last=datetime.now(timezone.utc),
            valid_to=utc_valid_to,
            rawtext=rawtext,
            url=raw_offer.url,
            img_url=raw_offer.img_url,
        )

**Comment by Cla33ic** [comment]
Hey I looked into it, and this is working fine for me.

```python
from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import TYPE_CHECKING

import schedule
from playwright.async_api import Error

from lootscraper.browser import get_new_page
from lootscraper.common import OfferDuration, OfferType, Source
from lootscraper.database import Offer
from lootscraper.scraper.scraper_base import OfferHandler, RawOffer, Scraper

if TYPE_CHECKING:
    from playwright.async_api import Locator, Page

logger = logging.getLogger(__name__)

BASE_URL = "https://store.epicgames.com"
OFFER_URL = BASE_URL + "/en-US/"


@dataclass(kw_only=True)
class EpicRawOffer(RawOffer):
    valid_to: str


class EpicGamesScraper(Scraper):
    @staticmethod
    def get_source() -> Source:
        return Source.EPIC

    @staticmethod
    def get_type() -> OfferType:
        return OfferType.GAME

    @staticmethod
    def get_schedule() -> list[schedule.Job]:
        return [
            schedule.every().day.at("11:05", "US/Eastern"),
            schedule.every().day.at("13:00", "US/Eastern"),
        ]

    @staticmethod
    def get_duration() -> OfferDuration:
        return OfferDuration.CLAIMABLE

    def offers_expected(self) -> bool:
        return True

    def get_offers_url(self) -> str:
        return OFFER_URL

    def get_page_ready_selector(self) -> str:
        return "h5:has-text('Free Games')"

    async def scrape(self) -> list[Offer]:
        logger.debug(f"Starting scrape for {self.get_source().value}")
        
        async with get_new_page(self.context) as page:
            logger.debug(f"Navigating to {self.get_offers_url()}")
            try:
                await page.goto(self.get_offers_url(), timeout=30000)
                logger.debug("Page loaded successfully")
            except Error:
                logger.exception("Couldn't load page")
                return []

            logger.debug("Starting page_loaded_hook (scrolling)")
            await self.page_loaded_hook(page)
            logger.debug("page_loaded_hook (scrolling) completed")

            logger.debug(f"Waiting for selector: {self.get_page_ready_selector()}")
            try:
                await page.wait_for_selector(self.get_page_ready_selector(), timeout=10000)
                logger.debug("Page ready selector found")
            except Error:
                logger.exception("Page ready selector not found")
                return []

            logger.debug("Starting to read offers")
            offers = await self.read_offers(page)
            logger.debug(f"Found {len(offers)} raw offers")

        logger.debug("Cleaning and processing offers")
        offers = self.clean_offers(offers)
        unique_offers = self.deduplicate_offers(offers)
        categorized_offers = self.categorize_offers(unique_offers)
        filtered_offers = self.filter_for_valid_offers(categorized_offers)

        logger.debug(f"Final number of valid offers: {len(filtered_offers)}")
        return filtered_offers

    async def page_loaded_hook(self, page: Page) -> None:
        logger.debug("Starting to scroll")
        await page.evaluate("window.scrollBy(0, 2000)")
        logger.debug("Scroll completed, waiting for 2 seconds")
        await page.wait_for_timeout(2000)
        logger.debug("Wait completed")

    async def read_offers(self, page: Page) -> list[Offer]:
        offers: list[Offer] = []
        for handler in self.get_offer_handlers(page):
            logger.debug(f"Processing offer handler: {handler}")
            offers_locator = handler.locator

            try:
                elements = await offers_locator.all()
                logger.debug(f"Found {len(elements)} elements")
            except Error:
                logger.exception("Couldn't find any offers")
                return []

            for i, element in enumerate(elements):
                logger.debug(f"Processing element {i+1}/{len(elements)}")
                try:
                    raw_offer = await handler.read_offer_func(element)
                    if raw_offer is None:
                        logger.debug(f"Element {i+1} did not yield a raw offer")
                        continue
                    logger.debug(f"Raw offer found: {raw_offer}")
                except Exception:
                    logger.exception(f"Couldn't parse element {i+1}")
                    continue

                try:
                    normalized_offer = handler.normalize_offer_func(raw_offer)
                    logger.debug(f"Normalized offer: {normalized_offer}")
                except Exception:
                    logger.exception(f"Couldn't normalize offer {raw_offer.title}")
                    continue

                offers.append(normalized_offer)

        return offers

    def get_offer_handlers(self, page: Page) -> list[OfferHandler]:
        return [
            OfferHandler(
                page.locator('//span[text()="Free Now"]//ancestor::a'),
                self.read_raw_offer,
                self.normalize_offer,
            ),
        ]

    async def read_raw_offer(self, element: Locator) -> RawOffer:
        logger.debug("Starting to read raw offer")
        await element.scroll_into_view_if_needed()
        logger.debug("Element scrolled into view")

        title = await element.locator("//h6").text_content()
        if title is None:
            logger.error("Couldn't find title")
            raise ValueError("Couldn't find title")
        logger.debug(f"Found title: {title}")

        valid_to = await element.locator('//span[text()="Free Now - "]/time[1]').get_attribute("datetime")
        if valid_to is None:
            logger.error(f"Couldn't find valid to for {title}")
            raise ValueError(f"Couldn't find valid to for {title}")
        logger.debug(f"Found valid_to: {valid_to}")

        url = await element.get_attribute("href")
        if url is None:
            logger.error(f"Couldn't find url for {title}")
            raise ValueError(f"Couldn't find url for {title}")
        if not url.startswith("http"):
            url = BASE_URL + url
        logger.debug(f"Found url: {url}")

        img_url = await element.locator("img").get_attribute("src")
        if img_url is None:
            logger.error(f"Couldn't find image for {title}")
            raise ValueError(f"Couldn't find image for {title}")
        logger.debug(f"Found img_url: {img_url}")

        return EpicRawOffer(title=title, valid_to=valid_to, url=url, img_url=img_url)

    def normalize_offer(self, raw_offer: RawOffer) -> Offer:
        if not isinstance(raw_offer, EpicRawOffer):
            raise TypeError("Wrong type of raw offer")

        rawtext = {"title": raw_offer.title, "enddate": raw_offer.valid_to}

        utc_valid_to = None
        if raw_offer.valid_to:
            try:
                utc_valid_to = datetime.strptime(raw_offer.valid_to, "%Y-%m-%dT%H:%M:%S.000Z").replace(tzinfo=timezone.utc)
            except ValueError:
                logger.exception(f"Couldn't parse valid_to date: {raw_offer.valid_to}")

        return Offer(
            source=EpicGamesScraper.get_source(),
            duration=EpicGamesScraper.get_duration(),
            type=EpicGamesScraper.get_type(),
            title=raw_offer.title,
            probable_game_name=raw_offer.title,
            seen_last=datetime.now(timezone.utc),
            valid_to=utc_valid_to,
            rawtext=rawtext,
            url=raw_offer.url,
            img_url=raw_offer.img_url,
        )

**Comment by eikowagenknecht** [comment]
Seems to work locally but not in my Docker environment.. will investigate this.

**Comment by eikowagenknecht** [comment]
On my locker Docker it was fine as well, but since this is runing on a slower Synology NAS in production, the page seems not to have loaded at that point. Added a short delay after scrolling to the bottom and now it seems to work again :-)

**Comment by RoseTheFlower** [comment]
The RSS feed is still stuck on Control. No word on Ghostrunner 2 or today's Hot Wheels Unleashed.

**Comment by eikowagenknecht** [comment]
Ugh sorry, the service stopped itself for unknown reasons. I restarted manually, offers should come in any minute now.
