### ISSUE TITLE
Create Discord channel

### ISSUE THREAD

**Issue by eikowagenknecht** [eikowagenknecht/lootscraper#27]
One more way for users to subscribe: Discord. Look into creating a server and design a method that pushes the updates there as well.

**Comment by louanfontenele** [comment]
If you need help to create, just call me on discord Louan#1802

**Comment by LEv145** [comment]
I tried to create: 
https://discord.gg/yzC5jkBQvt
![image](https://user-images.githubusercontent.com/40071054/193305449-11784382-6204-40eb-bf80-113234c7602c.png)

I use: https://github.com/synzen/MonitoRSS-Clone

**Comment by LEv145** [comment]
@eikowagenknecht @louanfontenele What do you think?
![изображение](https://user-images.githubusercontent.com/40071054/205756146-79897211-f233-4b87-a7eb-b06fcf222cc1.png)

**Comment by louanfontenele** [comment]
> @eikowagenknecht @louanfontenele What do you think?
> ![изображение](https://user-images.githubusercontent.com/40071054/205756146-79897211-f233-4b87-a7eb-b06fcf222cc1.png)
> 
> 

I think it's good, but creating a own bot I think it's better.

**Comment by LEv145** [comment]
> I think it's good, but creating a own bot I think it's better.

It will be more difficult, and I think announcement channels are not bad

**Comment by eikowagenknecht** [comment]
Unfortunately, I don't have enough free time at the moment to do more than maintenance and small improvements, so the Discord bot won't happen any time soon.

I think MonitoRSS will be a good workaround for a lot of use cases and have added a short paragraph on how to configure it to the README. I'll be closing all Discord related issues for the time being.
