### ISSUE TITLE
Support for telegram topics and channels !

### ISSUE THREAD

**Issue by hanialhusein** [eikowagenknecht/lootscraper#283]
### Is your feature request related to a problem? Please describe.

Hi !
Can you please make an option to let the bot posts in a specific group topic and channels ?

### Describe the solution you'd like

Command that links the bot to my super group and let me sends a command in a specific topic to confirm posting to this topic

**Comment by eikowagenknecht** [comment]
Thanks for the idea. This will need some refactoring because currently I use the users telegram_id, but this doesn't exist for chats. Chats have their own IDs though and that also goes for channels. So it should be possible :-)

Haven't looked into group topics yet, but hopefully it's the same there.

**Comment by eikowagenknecht** [comment]
This should be fully supported now. You can add the bot to a Channel, Group or Supergroup (Group with threads) now.

**Comment by hanialhusein** [comment]
Cool Thanks! 
But I didn't find any option that makes the bot post in a specific topic (Thread), That means that he will post in #General topic ?

**Comment by hanialhusein** [comment]
Or i can just send /start@LootScraperBot in the topic i want ?

**Comment by eikowagenknecht** [comment]
> Or i can just send /start@LootScraperBot in the topic i want ?

Yes, that is exactly what should work.

**Comment by eikowagenknecht** [comment]
> And can you let just the admin use the bot in groups?
> 
> Sorry for spamming messages, But I'm just keeping you updated about what i experienced with the bot 🙏🏻

Not sure if I can check for the group rights of the person sending the message.. I'll check if it can be done.

**Comment by eikowagenknecht** [comment]
So for channels there is unfortunately no way to let only the admin use the bot since channels are anonymous by design.

For groups and supergroups I added a check for the "admin" or "owner" rights, though :-)

**Comment by hanialhusein** [comment]
> So for channels there is unfortunately no way to let only the admin use the bot since channels are anonymous by design.
> 
> For groups and supergroups I added a check for the "admin" or "owner" rights, though :-)

Respect bro 🔥🤜🏻
