### ISSUE TITLE
Epic Games: wrong "Offer valid to" date

### ISSUE THREAD

**Issue by Hillcow** [eikowagenknecht/lootscraper#303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Regarding "Epic Games (Game) - Escape Academy"

Offer valid to: 2024-01-02 - 16:00

### Expected Behavior

Offer valid to: 2024-01-03 - 16:00

### Steps To Reproduce

https://feed.phenx.de/lootscraper_epic_game.xml

**Comment by eikowagenknecht** [comment]
Thanks, I'll have a look at it.

**Comment by eikowagenknecht** [comment]
Ghostrunner was valid to 2024-01-01 - 16:00
Escape Academy was valid to 2024-01-02 - 16:00
20 minutes till dawn was valid to 2024-01-03 - 16:00
A plague tale is valid to 2024-01-04 - 16:00

Looks fine to me. Why do you say Escape Academy should be valid to 2024-01-03 - 16:00?
