### ISSUE TITLE
Incorrect description for current game from Epic Games: LOVE

### ISSUE THREAD

**Issue by Cillu** [eikowagenknecht/lootscraper#310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Can be seen on the static HTML page and in the RSS feed here: https://feed.phenx.de/lootscraper_epic_game.xml

I know you have a disclaimer that the description of the game is automatically generated, however I just wanted to bring to your attention that the description for this game is actually for another game called "Love of Ren'ai Koutei of LOVE!"

### Expected Behavior

Link to game: https://store.epicgames.com/en-US/p/love-65c4d0

Proper description: Love is a reductive platforming game with a retro aesthetic and a focus on a challenging difficulty. It has an custom respawn system, 16 levels, 12 track soundtrack, and competitive scoring.

**Comment by eikowagenknecht** [comment]
Thanks for pointing this out. The game descriptions are taken from Steam and the Twitch DB. Usually problems arise when games are not in these databases (many itch.io titles and some non-Steam games like World of Warcraft).

In this case, however, it should have worked. It should have picked up this entry: https://store.steampowered.com/app/269270/LOVE/

I'll look into why it didn't.

**Comment by eikowagenknecht** [comment]
There seems to be an edge case where:
- Steam has the correct info (in this case https://store.steampowered.com/app/269270/LOVE/)
- IGDB returns a match as well, but it's a wrong one (in this case https://www.igdb.com/games/love-of-renai-koutei-of-love (172713), but it should have been https://www.igdb.com/games/love (16912)). When I call IGDB now, I get 284242 instead, so it varies.

I have added a check that uses an exact match when one source has an exact match and the other has not.
