### ISSUE TITLE
Thin out RSS feeds

### ISSUE THREAD

**Issue by eikowagenknecht** [eikowagenknecht/lootscraper#312]
### Is your feature request related to a problem? Please describe.

The RSS feeds contain *all* games that LootScraper has ever found. That's a lot of games, can lead to larger download sizes than necessary and even confuse some RSS readers.

### Describe the solution you'd like

Have only active listings in the RSS feeds, but keep all the listings in the HTML pages. We may want to link these as a "view older listings" link in the RSS feed as well.

**Comment by quelotic** [comment]
I've been trying to import the feed to "MonitoRSS" for discord, and since it's full of images, I can't!
Would be better to just share the link to the image instead of the full image!

**Comment by eikowagenknecht** [comment]
@quelotic The images in the feed are not a problem at all for MonitoRSS. In fact it's good they are included as `<img>` elements, because this way MonitoRSS can extract them and show them as embeds in Discord.

I just tried it with the Amazon Games feed and it works fine with the following settings:

Text > Content:

```
{{title}}

{{description}}
```

Embeds: One with only Image URL filled: `{{extracted::atom:content__#::image1}}`
Buttons: One with label `Claim` and URL `{{link}}`

Result:

![image](https://github.com/eikowagenknecht/lootscraper/assets/1475672/ffa52086-65bf-4c57-ab35-8c7f481b06d4)

The full feed is too large, though. It's currently at 9MB and MonitoRSS can only handle up to 3MB. This is exactly one of the cases where it would be better to only have current offers in the RSS feed and which is tracked in this issue.

**Comment by eikowagenknecht** [comment]
It's done, the main feed is currently down to 421 KB and should work with MonitoRSS just fine :-)
