### ISSUE TITLE
Template N8n rss to discord

### ISSUE THREAD

**Issue by JamesDAdams** [eikowagenknecht/lootscraper#320]
Hi, 

Thanks for the RSS, i use it in N8N for send message on discord thread and i share my template here is anyone need too :

<img width="259" alt="image" src="https://github.com/eikowagenknecht/lootscraper/assets/20860324/996fdbe1-1dc1-47e4-bedf-fcfac541ba89">

`{
  "name": "rss-free-games",
  "nodes": [
    {
      "parameters": {
        "pollTimes": {
          "item": [
            {
              "mode": "everyHour"
            }
          ]
        },
        "feedUrl": "https://feed.phenx.de/lootscraper_gog_game.xml"
      },
      "id": "116057ca-4bfd-4a0a-83c4-ceb320e5cec9",
      "name": "RSS Game Free Gog",
      "type": "n8n-nodes-base.rssFeedReadTrigger",
      "typeVersion": 1,
      "position": [
        680,
        720
      ]
    },
    {
      "parameters": {
        "pollTimes": {
          "item": [
            {
              "mode": "everyHour"
            }
          ]
        },
        "feedUrl": "https://feed.phenx.de/lootscraper_steam_game.xml"
      },
      "id": "f36cfe3d-fd81-4b52-a45c-3ec7bc1db8f0",
      "name": "RSS Game Free Steam",
      "type": "n8n-nodes-base.rssFeedReadTrigger",
      "typeVersion": 1,
      "position": [
        680,
        960
      ]
    },
    {
      "parameters": {
        "operation": "extractHtmlContent",
        "dataPropertyName": "content",
        "extractionValues": {
          "values": [
            {
              "key": "p",
              "cssSelector": "p",
              "returnArray": true
            },
            {
              "key": "li",
              "cssSelector": "li",
              "returnArray": true
            },
            {
              "key": "img",
              "cssSelector": "img",
              "returnValue": "attribute",
              "attribute": "src",
              "returnArray": true
            }
          ]
        },
        "options": {}
      },
      "id": "97aa327c-4e01-4954-8361-5eb4e2ab35d0",
      "name": "extract fields Steam",
      "type": "n8n-nodes-base.html",
      "typeVersion": 1.2,
      "position": [
        980,
        960
      ]
    },
    {
      "parameters": {
        "assignments": {
          "assignments": [
            {
              "id": "834ca178-6463-4f4c-b0fc-62366400a132",
              "name": "thread-id",
              "value": "1212861013557379142",
              "type": "string"
            },
            {
              "id": "19b988dc-4cf3-467c-a42b-cc093cd1c691",
              "name": "platformLogo",
              "value": "=https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Steam_icon_logo.svg/512px-Steam_icon_logo.svg.png",
              "type": "string"
            },
            {
              "id": "c3d5d691-8789-4828-bfdb-5f69016ed471",
              "name": "offer-valid-from",
              "value": "={{ $json[\"li\"][0].split(\"Offer valid from:\")[0].trim(); }}",
              "type": "string"
            },
            {
              "id": "9224e6e8-ece6-4540-b1c8-7b60b551bdaf",
              "name": "offer-valid-to",
              "value": "={{ $json[\"li\"][1].split(\"Offer valid to:\")[0].trim(); }}",
              "type": "string"
            },
            {
              "id": "8848d228-13b5-44e7-9d6e-811ac4aa799c",
              "name": "release-date",
              "value": "={{ $json[\"li\"][3].split(\"Release date:\")[0].trim(); }}",
              "type": "string"
            },
            {
              "id": "47bdd60f-aed9-48df-9d73-7a758eef3837",
              "name": "description",
              "value": "={{ $json[\"li\"][4].replace(/\\n|\\r/g, '').replace(/\\t/g, '') }}",
              "type": "string"
            },
            {
              "id": "0724b74a-6720-4b68-ad60-186a0d43b870",
              "name": "img",
              "value": "={{ $json[\"img\"][0] }}",
              "type": "string"
            },
            {
              "id": "21d76fa8-1f1b-4d7e-a526-b129173456e0",
              "name": "name",
              "value": "={{ $json[\"p\"][1].split(\"About the game (*):\")[1].trim() }}",
              "type": "string"
            },
            {
              "id": "e13ce8d3-4cae-4d11-a976-796e177e783e",
              "name": "rating-igdb",
              "value": "={{ $json[\"li\"][2].split(\"IGDB Meta\")[1].trim().split(\"%\")[0].trim() }}%",
              "type": "string"
            }
          ]
        },
        "options": {}
      },
      "id": "0a098718-99e6-4aa5-9631-6462d02ee128",
      "name": "Edit Fields Steam",
      "type": "n8n-nodes-base.set",
      "typeVersion": 3.3,
      "position": [
        1260,
        960
      ]
    },
    {
      "parameters": {
        "method": "POST",
        "url": "=https://discord.com/api/webhooks/WEBHOOK-ID?thread_id={{ $json['thread-id'] }}",
        "sendHeaders": true,
        "headerParameters": {
          "parameters": [
            {
              "name": "Content-Type",
              "value": "application/json"
            }
          ]
        },
        "sendBody": true,
        "specifyBody": "json",
        "jsonBody": "={\n    \"embeds\": [\n        {\n            \"color\": 4321431,\n            \"timestamp\": \"{{ $('RSS Game Free Steam').item.json['isoDate'] }}\",\n            \"url\": \"{{ $('RSS Game Free Steam').item.json['link'] }}\",\n            \"author\": {\n                \"url\": \"https://discord.com\"\n            },\n            \"image\": {\n                \"url\": \"{{ $json['img'] }}\"\n            },\n            \"footer\": {\n                \"icon_url\": \"https://cdn.discordapp.com/embed/avatars/0.png\"\n            },\n            \"fields\": [\n                {\n                    \"name\": \"Du\",\n                    \"value\": \"{{ $json['offer-valid-from'] }}\",\n                    \"inline\": true\n                },\n                {\n                    \"name\": \"Au\",\n                    \"inline\": true,\n                    \"value\": \"{{ $json['offer-valid-to'] }}\"\n                },\n                {\n                    \"name\": \"Date de sortie\",\n                    \"inline\": true,\n                    \"value\": \"{{ $json['release-date'] }}\"\n                },\n                {\n                    \"name\": \"Prix (Steam)\",\n                    \"inline\": true,\n                    \"value\": \"{{ $json['price'] }}\"\n                },\n                {\n                    \"name\": \"Note Steam\",\n                    \"inline\": true,\n                    \"value\": \"{{ $json['rating-steam'] }}\"\n                },\n                {\n                    \"name\": \"Note Igdb\",\n                    \"inline\": true,\n                    \"value\": \"{{ $json['rating-igdb'] }}\"\n                }\n            ],\n            \"title\": \"{{ $json['name'] }}\",\n            \"thumbnail\": {\n                \"url\": \"{{ $json['platformLogo'] }}\"\n            },\n            \"description\": \"{{ $json['description'] }}\"\n        }\n    ]\n}",
        "options": {}
      },
      "id": "4f663df6-dfc1-44de-bddd-4b76b2c4b946",
      "name": "Send notif Steam",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4.1,
      "position": [
        1540,
        960
      ]
    },
    {
      "parameters": {
        "operation": "extractHtmlContent",
        "dataPropertyName": "content",
        "extractionValues": {
          "values": [
            {
              "key": "p",
              "cssSelector": "p",
              "returnArray": true
            },
            {
              "key": "li",
              "cssSelector": "li",
              "returnArray": true
            },
            {
              "key": "img",
              "cssSelector": "img",
              "returnValue": "attribute",
              "attribute": "src",
              "returnArray": true
            }
          ]
        },
        "options": {}
      },
      "id": "21ed1c36-2808-4b72-aef9-763ad55e2a7f",
      "name": "extract fields Steam1",
      "type": "n8n-nodes-base.html",
      "typeVersion": 1.2,
      "position": [
        980,
        1160
      ]
    },
    {
      "parameters": {
        "assignments": {
          "assignments": [
            {
              "id": "834ca178-6463-4f4c-b0fc-62366400a132",
              "name": "thread-id",
              "value": "1212861013557379142",
              "type": "string"
            },
            {
              "id": "19b988dc-4cf3-467c-a42b-cc093cd1c691",
              "name": "platformLogo",
              "value": "=https://www.1min30.com/wp-content/uploads/2018/04/logo-Ubisoft.jpg",
              "type": "string"
            },
            {
              "id": "c3d5d691-8789-4828-bfdb-5f69016ed471",
              "name": "offer-valid-from",
              "value": "={{ $json[\"li\"][0].split(\"Offer valid from:\")[0].trim(); }}",
              "type": "string"
            },
            {
              "id": "9224e6e8-ece6-4540-b1c8-7b60b551bdaf",
              "name": "offer-valid-to",
              "value": "={{ $json[\"li\"][1].split(\"Offer valid to:\")[0].trim(); }}",
              "type": "string"
            },
            {
              "id": "47bdd60f-aed9-48df-9d73-7a758eef3837",
              "name": "description",
              "value": "=",
              "type": "string"
            },
            {
              "id": "0724b74a-6720-4b68-ad60-186a0d43b870",
              "name": "img",
              "value": "={{ $json[\"img\"][0] }}",
              "type": "string"
            },
            {
              "id": "21d76fa8-1f1b-4d7e-a526-b129173456e0",
              "name": "name",
              "value": "={{ $('RSS Game Free Ubisoft').item.json[\"title\"].split(\"Ubisoft (Game) - Get\")[1].trim().split(\"for free\")[0].trim(); }}",
              "type": "string"
            },
            {
              "id": "e13ce8d3-4cae-4d11-a976-796e177e783e",
              "name": "rating-igdb",
              "value": "=",
              "type": "string"
            }
          ]
        },
        "options": {}
      },
      "id": "6a98c538-35a8-4a7e-87c7-77bec22cb288",
      "name": "Edit Fields Steam1",
      "type": "n8n-nodes-base.set",
      "typeVersion": 3.3,
      "position": [
        1260,
        1160
      ]
    },
    {
      "parameters": {
        "pollTimes": {
          "item": [
            {
              "mode": "everyHour"
            }
          ]
        },
        "feedUrl": "https://feed.phenx.de/lootscraper_ubisoft_game.xml"
      },
      "id": "6be2148f-ccba-4a28-9416-edbdf1d54bca",
      "name": "RSS Game Free Ubisoft",
      "type": "n8n-nodes-base.rssFeedReadTrigger",
      "typeVersion": 1,
      "position": [
        680,
        1160
      ]
    },
    {
      "parameters": {
        "method": "POST",
        "url": "=https://discord.com/api/webhooks/WEBHOOK-ID?thread_id={{ $json['thread-id'] }}",
        "sendHeaders": true,
        "headerParameters": {
          "parameters": [
            {
              "name": "Content-Type",
              "value": "application/json"
            }
          ]
        },
        "sendBody": true,
        "specifyBody": "json",
        "jsonBody": "={\n    \"embeds\": [\n        {\n            \"color\": 4321431,\n            \"timestamp\": \"{{ $('RSS Game Free Ubisoft').item.json['isoDate'] }}\",\n            \"url\": \"{{ $('RSS Game Free Ubisoft').item.json['link'] }}\",\n            \"author\": {\n                \"url\": \"https://discord.com\"\n            },\n            \"image\": {\n                \"url\": \"{{ $json['img'] }}\"\n            },\n            \"footer\": {\n                \"icon_url\": \"https://cdn.discordapp.com/embed/avatars/0.png\"\n            },\n            \"fields\": [\n                {\n                    \"name\": \"Du\",\n                    \"value\": \"{{ $json['offer-valid-from'] }}\",\n                    \"inline\": true\n                },\n                {\n                    \"name\": \"Au\",\n                    \"inline\": true,\n                    \"value\": \"{{ $json['offer-valid-to'] }}\"\n                }\n            ],\n            \"title\": \"{{ $json['name'] }}\",\n            \"thumbnail\": {\n                \"url\": \"{{ $json['platformLogo'] }}\"\n            },\n            \"description\": \"{{ $json['description'] }}\"\n        }\n    ]\n}",
        "options": {}
      },
      "id": "6425b383-f72c-49e6-909a-022d75246885",
      "name": "Send notif ubisoft",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4.1,
      "position": [
        1540,
        1160
      ]
    },
    {
      "parameters": {
        "pollTimes": {
          "item": [
            {
              "mode": "everyHour"
            }
          ]
        },
        "feedUrl": "https://feed.phenx.de/lootscraper_amazon_game.xml"
      },
      "id": "ae4285cc-0b1e-4687-8ee3-9ad5f352795e",
      "name": "RSS Game Free Amazon",
      "type": "n8n-nodes-base.rssFeedReadTrigger",
      "typeVersion": 1,
      "position": [
        680,
        1380
      ]
    },
    {
      "parameters": {
        "operation": "extractHtmlContent",
        "dataPropertyName": "content",
        "extractionValues": {
          "values": [
            {
              "key": "p",
              "cssSelector": "p",
              "returnArray": true
            },
            {
              "key": "li",
              "cssSelector": "li",
              "returnArray": true
            },
            {
              "key": "img",
              "cssSelector": "img",
              "returnValue": "attribute",
              "attribute": "src",
              "returnArray": true
            }
          ]
        },
        "options": {}
      },
      "id": "ab7cf44c-5b46-4134-a16f-0553843aa07b",
      "name": "extract fields Amazon",
      "type": "n8n-nodes-base.html",
      "typeVersion": 1.2,
      "position": [
        980,
        1380
      ]
    },
    {
      "parameters": {
        "assignments": {
          "assignments": [
            {
              "id": "834ca178-6463-4f4c-b0fc-62366400a132",
              "name": "thread-id",
              "value": "1212861013557379142",
              "type": "string"
            },
            {
              "id": "19b988dc-4cf3-467c-a42b-cc093cd1c691",
              "name": "platformLogo",
              "value": "=https://static.amazon.jobs/teams/7/thumbnails/AG_logo_PrimaryGold_onblack.jpg?1657636607",
              "type": "string"
            },
            {
              "id": "c3d5d691-8789-4828-bfdb-5f69016ed471",
              "name": "offer-valid-from",
              "value": "={{ $json[\"li\"][0].split(\"Offer valid from:\")[0].trim(); }}",
              "type": "string"
            },
            {
              "id": "9224e6e8-ece6-4540-b1c8-7b60b551bdaf",
              "name": "offer-valid-to",
              "value": "={{ $json[\"li\"][1].split(\"Offer valid to:\")[0].trim(); }}",
              "type": "string"
            },
            {
              "id": "ef7bda11-6c31-4b85-beb4-477f687a9788",
              "name": "rating-steam",
              "value": "={{ $json[\"li\"][2].split(\"Ratings:Steam\")[1].trim().split(\"%\")[0].trim() }}%",
              "type": "string"
            },
            {
              "id": "8848d228-13b5-44e7-9d6e-811ac4aa799c",
              "name": "release-date",
              "value": "={{ $json[\"li\"][3].split(\"Release date:\")[0].trim(); }}",
              "type": "string"
            },
            {
              "id": "2e30097e-ef75-4f9a-a93f-8369b4e64de0",
              "name": "price",
              "value": "={{ $json[\"li\"][4].split(\"Recommended price\")[0].trim(); }}",
              "type": "string"
            },
            {
              "id": "47bdd60f-aed9-48df-9d73-7a758eef3837",
              "name": "description",
              "value": "={{ $json[\"li\"][5].replace(/\\n|\\r/g, '').replace(/\\t/g, '') }}",
              "type": "string"
            },
            {
              "id": "8484b92f-6fb4-48d8-8bfc-215ca6355bf3",
              "name": "categories",
              "value": "={{ $json[\"li\"][6].split(\"Genres:\")[0].trim(); }}",
              "type": "string"
            },
            {
              "id": "2c6b22ed-92cf-432b-895c-ab676ca9f777",
              "name": "rating-igdb",
              "value": "={{ $json[\"li\"][2].split(\"IGDB Meta\")[1].trim().split(\"%\")[0].trim() }}%",
              "type": "string"
            },
            {
              "id": "0724b74a-6720-4b68-ad60-186a0d43b870",
              "name": "img",
              "value": "={{ $json[\"img\"][0] }}",
              "type": "string"
            },
            {
              "id": "21d76fa8-1f1b-4d7e-a526-b129173456e0",
              "name": "name",
              "value": "={{ $json[\"p\"][1].split(\"About the game (*):\")[1].trim() }}",
              "type": "string"
            }
          ]
        },
        "options": {}
      },
      "id": "b297c56a-ef8d-47e1-a0f0-738bde60480f",
      "name": "Edit Amazon",
      "type": "n8n-nodes-base.set",
      "typeVersion": 3.3,
      "position": [
        1260,
        1380
      ]
    },
    {
      "parameters": {
        "method": "POST",
        "url": "=https://discord.com/api/webhooks/WEBHOOK-ID?thread_id={{ $json['thread-id'] }}",
        "sendHeaders": true,
        "headerParameters": {
          "parameters": [
            {
              "name": "Content-Type",
              "value": "application/json"
            }
          ]
        },
        "sendBody": true,
        "specifyBody": "json",
        "jsonBody": "={\n    \"embeds\": [\n        {\n            \"color\": 4321431,\n            \"timestamp\": \"{{ $('RSS Game Free Amazon').item.json['isoDate'] }}\",\n            \"url\": \"{{ $('RSS Game Free Amazon').item.json['link'] }}\",\n            \"author\": {\n                \"url\": \"https://discord.com\"\n            },\n            \"image\": {\n                \"url\": \"{{ $json['img'] }}\"\n            },\n            \"footer\": {\n                \"icon_url\": \"https://cdn.discordapp.com/embed/avatars/0.png\"\n            },\n            \"fields\": [\n                {\n                    \"name\": \"Du\",\n                    \"value\": \"{{ $json['offer-valid-from'] }}\",\n                    \"inline\": true\n                },\n                {\n                    \"name\": \"Au\",\n                    \"inline\": true,\n                    \"value\": \"{{ $json['offer-valid-to'] }}\"\n                },\n                {\n                    \"name\": \"Date de sortie\",\n                    \"inline\": true,\n                    \"value\": \"{{ $json['release-date'] }}\"\n                },\n                {\n                    \"name\": \"Prix (Steam)\",\n                    \"inline\": true,\n                    \"value\": \"{{ $json['price'] }}\"\n                },\n                {\n                    \"name\": \"Note Steam\",\n                    \"inline\": true,\n                    \"value\": \"{{ $json['rating-steam'] }}\"\n                },\n                {\n                    \"name\": \"Note Igdb\",\n                    \"inline\": true,\n                    \"value\": \"{{ $json['rating-igdb'] }}\"\n                },\n                {\n                    \"name\": \"Genres\",\n                    \"inline\": true,\n                    \"value\": \"{{ $json['categories'] }}\"\n                }\n            ],\n            \"title\": \"{{ $json['name'] }}\",\n            \"thumbnail\": {\n                \"url\": \"{{ $json['platformLogo'] }}\"\n            },\n            \"description\": \"{{ $json['description'] }}\"\n        }\n    ]\n}",
        "options": {}
      },
      "id": "89f08863-1084-41f4-959e-3178f92a201e",
      "name": "Send notif Discord2",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4.1,
      "position": [
        1540,
        1380
      ]
    },
    {
      "parameters": {
        "pollTimes": {
          "item": [
            {
              "mode": "everyHour"
            }
          ]
        },
        "feedUrl": "https://feed.phenx.de/lootscraper_epic_game.xml"
      },
      "id": "812af46c-b080-448a-8df1-5f6895a7520a",
      "name": "RSS Game Free Epic",
      "type": "n8n-nodes-base.rssFeedReadTrigger",
      "typeVersion": 1,
      "position": [
        680,
        500
      ]
    },
    {
      "parameters": {
        "operation": "extractHtmlContent",
        "dataPropertyName": "content",
        "extractionValues": {
          "values": [
            {
              "key": "p",
              "cssSelector": "p",
              "returnArray": true
            },
            {
              "key": "li",
              "cssSelector": "li",
              "returnArray": true
            },
            {
              "key": "img",
              "cssSelector": "img",
              "returnValue": "attribute",
              "attribute": "src",
              "returnArray": true
            }
          ]
        },
        "options": {}
      },
      "id": "7e29fb33-cfa1-459b-a495-8c352366954c",
      "name": "extract fields Epic",
      "type": "n8n-nodes-base.html",
      "typeVersion": 1.2,
      "position": [
        980,
        500
      ]
    },
    {
      "parameters": {
        "assignments": {
          "assignments": [
            {
              "id": "834ca178-6463-4f4c-b0fc-62366400a132",
              "name": "thread-id",
              "value": "1212861013557379142",
              "type": "string"
            },
            {
              "id": "19b988dc-4cf3-467c-a42b-cc093cd1c691",
              "name": "platformLogo",
              "value": "=https://upload.wikimedia.org/wikipedia/commons/a/a7/Epic_Games_logo.png",
              "type": "string"
            },
            {
              "id": "c3d5d691-8789-4828-bfdb-5f69016ed471",
              "name": "offer-valid-from",
              "value": "={{ $json[\"li\"][0].split(\"Offer valid from:\")[0].trim(); }}",
              "type": "string"
            },
            {
              "id": "9224e6e8-ece6-4540-b1c8-7b60b551bdaf",
              "name": "offer-valid-to",
              "value": "={{ $json[\"li\"][1].split(\"Offer valid to:\")[0].trim(); }}",
              "type": "string"
            },
            {
              "id": "ef7bda11-6c31-4b85-beb4-477f687a9788",
              "name": "rating-steam",
              "value": "={{ $json[\"li\"][2].split(\"Ratings:Steam\")[1].trim().split(\"%\")[0].trim() }}%",
              "type": "string"
            },
            {
              "id": "8848d228-13b5-44e7-9d6e-811ac4aa799c",
              "name": "release-date",
              "value": "={{ $json[\"li\"][3].split(\"Release date:\")[0].trim(); }}",
              "type": "string"
            },
            {
              "id": "2e30097e-ef75-4f9a-a93f-8369b4e64de0",
              "name": "price",
              "value": "={{ $json[\"li\"][4].split(\"Recommended price\")[0].trim(); }}",
              "type": "string"
            },
            {
              "id": "47bdd60f-aed9-48df-9d73-7a758eef3837",
              "name": "description",
              "value": "={{ $json[\"li\"][5].replace(/\\n|\\r/g, '').replace(/\\t/g, '') }}",
              "type": "string"
            },
            {
              "id": "8484b92f-6fb4-48d8-8bfc-215ca6355bf3",
              "name": "categories",
              "value": "={{ $json[\"li\"][6] }}",
              "type": "string"
            },
            {
              "id": "2c6b22ed-92cf-432b-895c-ab676ca9f777",
              "name": "rating-igdb",
              "value": "={{ $json[\"li\"][2].split(\"IGDB Meta\")[1].trim().split(\"%\")[0].trim() }}%",
              "type": "string"
            },
            {
              "id": "0724b74a-6720-4b68-ad60-186a0d43b870",
              "name": "img",
              "value": "={{ $json[\"img\"][0] }}",
              "type": "string"
            },
            {
              "id": "21d76fa8-1f1b-4d7e-a526-b129173456e0",
              "name": "name",
              "value": "={{ $json[\"p\"][1].split(\"About the game (*):\")[1].trim() }}",
              "type": "string"
            }
          ]
        },
        "options": {}
      },
      "id": "29443446-85ea-46c7-a3e6-4257c4e73953",
      "name": "Edit Fields Epic",
      "type": "n8n-nodes-base.set",
      "typeVersion": 3.3,
      "position": [
        1260,
        500
      ]
    },
    {
      "parameters": {
        "operation": "extractHtmlContent",
        "dataPropertyName": "content",
        "extractionValues": {
          "values": [
            {
              "key": "p",
              "cssSelector": "p",
              "returnArray": true
            },
            {
              "key": "li",
              "cssSelector": "li",
              "returnArray": true
            },
            {
              "key": "img",
              "cssSelector": "img",
              "returnValue": "attribute",
              "attribute": "src",
              "returnArray": true
            }
          ]
        },
        "options": {}
      },
      "id": "4d23d83b-1860-475f-9e55-7c5faee7497e",
      "name": "extract fields Gog",
      "type": "n8n-nodes-base.html",
      "typeVersion": 1.2,
      "position": [
        980,
        720
      ]
    },
    {
      "parameters": {
        "assignments": {
          "assignments": [
            {
              "id": "834ca178-6463-4f4c-b0fc-62366400a132",
              "name": "thread-id",
              "value": "1212861013557379142",
              "type": "string"
            },
            {
              "id": "19b988dc-4cf3-467c-a42b-cc093cd1c691",
              "name": "platformLogo",
              "value": "=https://prowly-uploads.s3.eu-west-1.amazonaws.com/uploads/23079/assets/466741/large-15d1a8a4728d6f38d44dd4edbe59f34a.png",
              "type": "string"
            },
            {
              "id": "c3d5d691-8789-4828-bfdb-5f69016ed471",
              "name": "offer-valid-from",
              "value": "={{ $json[\"li\"][0].split(\"Offer valid from:\")[0].trim(); }}",
              "type": "string"
            },
            {
              "id": "9224e6e8-ece6-4540-b1c8-7b60b551bdaf",
              "name": "offer-valid-to",
              "value": "={{ $json[\"li\"][1].split(\"Offer valid to:\")[0].trim(); }}",
              "type": "string"
            },
            {
              "id": "8848d228-13b5-44e7-9d6e-811ac4aa799c",
              "name": "release-date",
              "value": "={{ $json[\"li\"][2].split(\"Release date:\")[0].trim(); }}",
              "type": "string"
            },
            {
              "id": "47bdd60f-aed9-48df-9d73-7a758eef3837",
              "name": "description",
              "value": "={{ $json[\"li\"][3].replace(/\\n|\\r/g, '').replace(/\\t/g, '') }}",
              "type": "string"
            },
            {
              "id": "0724b74a-6720-4b68-ad60-186a0d43b870",
              "name": "img",
              "value": "={{ $json[\"img\"][0] }}",
              "type": "string"
            },
            {
              "id": "21d76fa8-1f1b-4d7e-a526-b129173456e0",
              "name": "name",
              "value": "={{ $json[\"p\"][1].split(\"About the game (*):\")[1].trim() }}",
              "type": "string"
            }
          ]
        },
        "options": {}
      },
      "id": "462185c4-5185-4940-81d9-0a84bd51f181",
      "name": "Edit Fields Gog",
      "type": "n8n-nodes-base.set",
      "typeVersion": 3.3,
      "position": [
        1260,
        720
      ]
    },
    {
      "parameters": {
        "method": "POST",
        "url": "=https://discord.com/api/webhooks/WEBHOOK-ID?thread_id={{ $json['thread-id'] }}",
        "sendHeaders": true,
        "headerParameters": {
          "parameters": [
            {
              "name": "Content-Type",
              "value": "application/json"
            }
          ]
        },
        "sendBody": true,
        "specifyBody": "json",
        "jsonBody": "={\n    \"embeds\": [\n        {\n            \"color\": 4321431,\n            \"timestamp\": \"{{ $('RSS Game Free Gog').item.json['isoDate'] }}\",\n            \"url\": \"{{ $('RSS Game Free Gog').item.json['link'] }}\",\n            \"author\": {\n                \"url\": \"https://discord.com\"\n            },\n            \"image\": {\n                \"url\": \"{{ $json['img'] }}\"\n            },\n            \"footer\": {\n                \"icon_url\": \"https://cdn.discordapp.com/embed/avatars/0.png\"\n            },\n            \"fields\": [\n                {\n                    \"name\": \"Du\",\n                    \"value\": \"{{ $json['offer-valid-from'] }}\",\n                    \"inline\": true\n                },\n                {\n                    \"name\": \"Au\",\n                    \"inline\": true,\n                    \"value\": \"{{ $json['offer-valid-to'] }}\"\n                },\n                {\n                    \"name\": \"Date de sortie\",\n                    \"inline\": true,\n                    \"value\": \"{{ $json['release-date'] }}\"\n                }\n            ],\n            \"title\": \"{{ $json['name'] }}\",\n            \"thumbnail\": {\n                \"url\": \"{{ $json['platformLogo'] }}\"\n            },\n            \"description\": \"{{ $json['description'] }}\"\n        }\n    ]\n}",
        "options": {}
      },
      "id": "b0ab08a3-e7c4-418d-a012-1bc6d794beb5",
      "name": "Send notif Discord Gog",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4.1,
      "position": [
        1540,
        720
      ]
    },
    {
      "parameters": {
        "method": "POST",
        "url": "=https://discord.com/api/webhooks/WEBHOOK-ID?thread_id={{ $json['thread-id'] }}",
        "sendHeaders": true,
        "headerParameters": {
          "parameters": [
            {
              "name": "Content-Type",
              "value": "application/json"
            }
          ]
        },
        "sendBody": true,
        "specifyBody": "json",
        "jsonBody": "={\n    \"embeds\": [\n        {\n            \"color\": 4321431,\n            \"timestamp\": \"{{ $('RSS Game Free Epic').item.json['isoDate'] }}\",\n            \"url\": \"{{ $('RSS Game Free Epic').item.json['link'] }}\",\n            \"author\": {\n                \"url\": \"https://discord.com\"\n            },\n            \"image\": {\n                \"url\": \"{{ $json['img'] }}\"\n            },\n            \"footer\": {\n                \"icon_url\": \"https://cdn.discordapp.com/embed/avatars/0.png\"\n            },\n            \"fields\": [\n                {\n                    \"name\": \"Du\",\n                    \"value\": \"{{ $json['offer-valid-from'] }}\",\n                    \"inline\": true\n                },\n                {\n                    \"name\": \"Au\",\n                    \"inline\": true,\n                    \"value\": \"{{ $json['offer-valid-to'] }}\"\n                },\n                {\n                    \"name\": \"Date de sortie\",\n                    \"inline\": true,\n                    \"value\": \"{{ $json['release-date'] }}\"\n                },\n                {\n                    \"name\": \"Prix (Steam)\",\n                    \"inline\": true,\n                    \"value\": \"{{ $json['price'] }}\"\n                },\n                {\n                    \"name\": \"Note Steam\",\n                    \"inline\": true,\n                    \"value\": \"{{ $json['rating-steam'] }}\"\n                },\n                {\n                    \"name\": \"Note Igdb\",\n                    \"inline\": true,\n                    \"value\": \"{{ $json['rating-igdb'] }}\"\n                },\n                {\n                    \"name\": \"Genres\",\n                    \"inline\": true,\n                    \"value\": \"{{ $json['categories'] }}\"\n                }\n            ],\n            \"title\": \"{{ $json['name'] }}\",\n            \"thumbnail\": {\n                \"url\": \"{{ $json['platformLogo'] }}\"\n            },\n            \"description\": \"{{ $json['description'] }}\"\n        }\n    ]\n}",
        "options": {}
      },
      "id": "fb1fc792-2f86-4008-95be-7c41c7e84753",
      "name": "Send notif Discord Epic",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 4.1,
      "position": [
        1540,
        500
      ]
    }
  ],
  "pinData": {},
  "connections": {
    "RSS Game Free Gog": {
      "main": [
        [
          {
            "node": "extract fields Gog",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "RSS Game Free Steam": {
      "main": [
        [
          {
            "node": "extract fields Steam",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "extract fields Steam": {
      "main": [
        [
          {
            "node": "Edit Fields Steam",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Edit Fields Steam": {
      "main": [
        [
          {
            "node": "Send notif Steam",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "extract fields Steam1": {
      "main": [
        [
          {
            "node": "Edit Fields Steam1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Edit Fields Steam1": {
      "main": [
        [
          {
            "node": "Send notif ubisoft",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "RSS Game Free Ubisoft": {
      "main": [
        [
          {
            "node": "extract fields Steam1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "RSS Game Free Amazon": {
      "main": [
        [
          {
            "node": "extract fields Amazon",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "extract fields Amazon": {
      "main": [
        [
          {
            "node": "Edit Amazon",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Edit Amazon": {
      "main": [
        [
          {
            "node": "Send notif Discord2",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "RSS Game Free Epic": {
      "main": [
        [
          {
            "node": "extract fields Epic",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "extract fields Epic": {
      "main": [
        [
          {
            "node": "Edit Fields Epic",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Edit Fields Epic": {
      "main": [
        [
          {
            "node": "Send notif Discord Epic",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "extract fields Gog": {
      "main": [
        [
          {
            "node": "Edit Fields Gog",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Edit Fields Gog": {
      "main": [
        [
          {
            "node": "Send notif Discord Gog",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "active": false,
  "settings": {
    "executionOrder": "v1"
  },
  "versionId": "86f2cebb-a978-49ab-b466-cbf12549ce71",
  "meta": {
    "templateCredsSetupCompleted": true,
    "instanceId": "6506495f22fb0b37b49c12e74b502818d201cb1c3d18b1c98e28beb8da7f5487"
  },
  "id": "hL3UIJYG9adXOUpQ",
  "tags": []
}`

**Comment by eikowagenknecht** [comment]
Thank you, that looks great! I'll be closing this issue, because it's not actionable, but it will stay here for others to find :-)
