### ISSUE TITLE
Detection whether a game is always free on GoG does not work

### ISSUE THREAD

**Issue by TrueMilli** [eikowagenknecht/lootscraper#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Gwent is detected as valid offer even tho it's free forever.

Url: https://www.gog.com/en/game/gwent_the_witcher_card_game

### Expected Behavior

Gwent is not considered as an offer.

### Steps To Reproduce

Run GoG Game Scraper.

### Anything else?

As soon as there is a new real offer from GoG compare what differs. I assume the claim button does not say "Play for Free" or there is a price instead of FREE: 
![image](https://user-images.githubusercontent.com/61841994/178140140-a443dcce-b7f3-4dfc-b208-9a45824983be.png)

**Comment by eikowagenknecht** [comment]
Can't be reproduced without another "free" offer from GOG in this format. Might be fixed in v1.0. Please reopen if you spot another one.
