### ISSUE TITLE
Support for time zone changes.

### ISSUE THREAD

**Issue by louanfontenele** [eikowagenknecht/lootscraper#89]
### Is your feature request related to a problem? Please describe.

It would be interesting if there was a way to change the bot's time zone to correspond with the country's time.

### Describe the solution you'd like

Create an option to change the time zone in the bot.

**Comment by louanfontenele** [comment]
> Thanks. I'm currently not at home, but will have a look at it sometime next week probably. Shouldn't be too hard to implement.

hope it work. thanks

**Comment by eikowagenknecht** [comment]
Took me a bit longer than anticipated thanks to a certain pandemic..

The new version is being deployed as I type, you can now use /timezone to choose a timezone offset.

**Comment by louanfontenele** [comment]
> Took me a bit longer than anticipated thanks to a certain pandemic..
> 
> The new version is being deployed as I type, you can now use /timezone to choose a timezone offset.

Thank you so much. Now to be more perfect, only thing missing is Multi-language support. Thanks for timezone.
