### ISSUE TITLE
Discord Bot

### ISSUE THREAD

**Issue by louanfontenele** [eikowagenknecht/lootscraper#90]
### Is your feature request related to a problem? Please describe.

Create a discord bot (open source code) that can send all offers in a channel, similar to what the Telegram bot already does.

**Comment by eikowagenknecht** [comment]
Unfortunately, I don't have enough free time at the moment to do more than maintenance and small improvements, so the Discord bot won't happen any time soon.

I think MonitoRSS will be a good workaround for a lot of use cases and have added a short paragraph on how to configure it to the README. I'll be closing all Discord related issues for the time being.
