### ISSUE TITLE
Discord addon for Brayanbot

### ISSUE THREAD

**Issue by louanfontenele** [eikowagenknecht/lootscraper#91]
### Is your feature request related to a problem? Please describe.

There is a modular bot called [Brayanbot](https://github.com/brayanbot/brayanbot), which is developed in Javascript. It would be nice to have an addon that could send notifications to members of what offers are available, which could be used on command and automatically sent as soon as a new offer arrived.

**Comment by eikowagenknecht** [comment]
#90 already requests a Discord bot. What is the benefit of this "Brayanbot"?

**Comment by louanfontenele** [comment]
It's a modular bot, instead of building a bot from scratch, you just create an addon/plugin for the bot.

**Comment by louanfontenele** [comment]
> #90 already requests a Discord bot. What is the benefit of this "Brayanbot"?

It's a modular bot, instead of building a bot from scratch, you just create an addon/plugin for the bot.
